/** Frozen from a live GDELT pull; regenerated by `npm run freeze-news`. Real headlines only. */
export const NEWS_FALLBACK_AS_OF = "2026-09-03";
export const NEWS_FALLBACK: { title: string; url: string; domain: string; seen: string }[] = [
  {
    "title": "Supersized El Nino may become strongest ever recorded",
    "url": "https://www.crookwellgazette.com.au/story/9343488/supersized-el-nino-may-become-strongest-ever-recorded/",
    "domain": "crookwellgazette.com.au",
    "seen": "2026-09-03T16:15:00Z"
  },
  {
    "title": "Indonesia food security remains secure amid El Nino, minister says",
    "url": "https://en.antaranews.com/news/429795/indonesias-food-security-remains-secure-amid-el-nino-minister-says",
    "domain": "en.antaranews.com",
    "seen": "2026-09-03T15:45:00Z"
  },
  {
    "title": "BoM forecasts strongest El Niño on record as research points to alarming climate change influence",
    "url": "https://www.theguardian.com/australia-news/2026/sep/04/bom-forecasts-strongest-el-nino-on-record-as-research-points-to-alarming-climate-change-influence",
    "domain": "theguardian.com",
    "seen": "2026-09-03T15:30:00Z"
  },
  {
    "title": "El Niño To Become Very Strong, Raising Risks Of Extreme Weather Into 2027",
    "url": "https://www.rttnews.com/story.aspx?Id=3688254",
    "domain": "rttnews.com",
    "seen": "2026-09-03T15:30:00Z"
  },
  {
    "title": "IOM Seeks $110M to Shield 4.9M from El Niño Effects",
    "url": "https://www.miragenews.com/iom-seeks-110m-to-shield-4-9m-from-el-nino-1738318/",
    "domain": "miragenews.com",
    "seen": "2026-09-03T15:15:00Z"
  },
  {
    "title": "WMO: Strengthening El Nino Raises Flood, Drought Risks",
    "url": "https://en.tempo.co/read/2118898/wmo-strengthening-el-nino-raises-flood-drought-risks",
    "domain": "en.tempo.co",
    "seen": "2026-09-03T15:15:00Z"
  },
  {
    "title": "UN warns El Nino could be off the chart, strongest in decades",
    "url": "https://www.aljazeera.com/news/2026/9/3/un-warns-el-nino-could-be-off-the-charts-strongest-in-decades",
    "domain": "aljazeera.com",
    "seen": "2026-09-03T12:45:00Z"
  },
  {
    "title": "Supersized El Nino to persist into 2027, UN says",
    "url": "https://dailynews.co.tz/supersized-el-nino-to-persist-into-2027-un-says/",
    "domain": "dailynews.co.tz",
    "seen": "2026-09-03T12:45:00Z"
  },
  {
    "title": "Indonesia fires: Toxic haze spreads across South East Asia amid super El Niño",
    "url": "https://www.bbc.com/news/articles/clyqw44w142o",
    "domain": "bbc.com",
    "seen": "2026-09-03T12:15:00Z"
  },
  {
    "title": "Floods, Droughts, Heatwaves Loom As Supersized El Niño Threatens Global Weather UN",
    "url": "https://leadership.ng/floods-droughts-heatwaves-loom-as-supersized-el-nino-threatens-global-weather-un/",
    "domain": "leadership.ng",
    "seen": "2026-09-03T12:15:00Z"
  },
  {
    "title": "From drought to deluge: How El Nino and compound climate disasters worsened the Grand Canyon tragedy",
    "url": "https://www.hindustantimes.com/ht-explainers/arizona-monsoon-rains-drought-wildfire-el-nino-worsen-floods-in-grand-canyon-101788432176754.html",
    "domain": "hindustantimes.com",
    "seen": "2026-09-03T12:15:00Z"
  },
  {
    "title": "El Nino to be very strong, last until February, UN warns",
    "url": "http://www.thejakartapost.com/culture/2026/09/03/el-nino-to-be-very-strong-last-until-february-un-warns",
    "domain": "thejakartapost.com",
    "seen": "2026-09-03T11:00:00Z"
  }
];
