/** Pulls GDELT live, runs the same filter the site uses, and freezes the result as the archive set. */
import { writeFileSync } from "node:fs";
import { fetchGdelt, selectNews } from "@/lib/sources/news";

async function main() {
const items = selectNews(await fetchGdelt(), 12);
if (items.length < 4) throw new Error(`only ${items.length} items — not freezing`);
const rows = items.map(({ title, url, domain, seen }) => ({ title, url, domain, seen }));
const out = `/** Frozen from a live GDELT pull; regenerated by \`npm run freeze-news\`. Real headlines only. */
export const NEWS_FALLBACK_AS_OF = ${JSON.stringify(new Date().toISOString().slice(0, 10))};
export const NEWS_FALLBACK: { title: string; url: string; domain: string; seen: string }[] = ${JSON.stringify(rows, null, 2)};
`;
writeFileSync("lib/sources/newsFallback.ts", out);
for (const r of items) console.log(r.seen, `[${r.badge}]`, r.tier, r.title, "→", r.url);
}

main().catch((e) => { console.error(e); process.exit(1); });
