import { chromium } from "playwright-core";
const S = "/tmp/claude-0/-home-user-eltrack/22b0563f-70d4-5e87-bf7e-22d8d53f27b7/scratchpad";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
await page.goto("http://localhost:3100/", { waitUntil: "load" });
await page.waitForFunction(() => document.querySelectorAll('g[role="button"]').length > 10, null, { timeout: 30000 });
await page.waitForTimeout(500);
await page.locator('g[aria-label^="Buoy 0n140w"]').click();
await page.waitForTimeout(300);
await page.locator('section[aria-labelledby="basin-title"]').screenshot({ path: `${S}/p3-buoy.png` });
await page.waitForFunction(() => document.querySelectorAll('tr.row-btn').length > 5, null, { timeout: 30000 });
await page.locator('tr.row-btn').nth(1).click();
await page.waitForTimeout(400);
await page.locator('section[aria-labelledby="oni-history-title"]').screenshot({ path: `${S}/p3-oni.png` });
await page.locator('section[aria-labelledby="events-title"]').screenshot({ path: `${S}/p3-events.png` });
await page.locator('section[aria-labelledby="plume-title"]').screenshot({ path: `${S}/p3-plume.png` });
await page.locator('section[aria-labelledby="subsurface-title"]').screenshot({ path: `${S}/p3-sub.png` });
await page.locator('.term-btn').first().hover();
await page.waitForTimeout(300);
await page.locator('section[aria-labelledby="current-title"]').screenshot({ path: `${S}/p3-term.png` });
await page.screenshot({ path: `${S}/p3-full.png`, fullPage: true });
await browser.close();
console.log("ok");
